import Link from 'next/link';

/*
 * ─────────────────────────────────────────────────────────────────────────────
 * FOR WHOEVER DEPLOYS THIS — READ BEFORE LAUNCH
 *
 * Accurate about how the software behaves, and not reviewed by a lawyer. The
 * enforceability of a liability limitation, and what a disclaimer must say to
 * work at all, both depend on your jurisdiction and neither is something this
 * document can settle on your behalf.
 *
 * Fill in CONTACT and GOVERNING_LAW, and have this reviewed before you accept a
 * user who is not you.
 * ─────────────────────────────────────────────────────────────────────────────
 */

// TODO(deploy): a real monitored address, and the jurisdiction you operate from.
const CONTACT = 'the project maintainer via the GitHub repository';
const GOVERNING_LAW = 'the jurisdiction in which the operator of this instance is established';

export const metadata = {
  title: 'Terms of Service — WanderForge',
  description: 'The terms you agree to when using WanderForge.',
};

const LAST_UPDATED = '21 August 2026';

export default function TermsPage() {
  return (
    <article>
      <h1>Terms of Service</h1>
      <p className="legal__meta">Last updated {LAST_UPDATED}</p>

      <p className="legal__lead">
        WanderForge is a free trip planner. Using it means agreeing to what
        follows. It is short on purpose.
      </p>

      <h2>The one that actually matters</h2>
      <p>
        <strong>
          Itineraries are generated by an AI and are suggestions, not advice.
        </strong>{' '}
        WanderForge checks each plan against estimated road distances and flags
        journeys that will not fit the time allowed, which catches a great deal.
        It does not know real opening hours, closures, weather on the day, road
        conditions, whether a place still exists, or whether it is safe to go
        there. Costs are estimates and will be wrong.
      </p>
      <p>
        Check anything that matters before you rely on it — particularly bookings,
        border requirements, and travel in remote or unfamiliar places. Do not use
        an itinerary from this or any other planner as your only source for a
        decision with real consequences.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You need an account, and you are responsible for what happens under it.</li>
        <li>Use an email address you control.</li>
        <li>One person per account. Invite collaborators rather than sharing a login.</li>
      </ul>

      <h2>Your content</h2>
      <p>
        Your trips are yours. Nothing here transfers ownership. Storing and
        processing them to make the service work — including sending the parts
        listed in the <Link href="/legal/privacy">Privacy Policy</Link> to the AI
        and mapping providers — is permission to operate, nothing more. It is not
        a licence to publish, sell or train on your content.
      </p>
      <p>
        Marking a trip public makes it readable by anyone with the link, which is
        a choice you make deliberately and can reverse.
      </p>

      <h2>What not to do</h2>
      <ul>
        <li>
          Do not use it to plan anything illegal, or to store content that is
          unlawful where you are.
        </li>
        <li>
          Do not attempt to reach other people&apos;s trips, or to work around the
          access rules.
        </li>
        <li>
          Do not automate against it in a way that degrades it for other people.
          The AI and mapping providers behind it are metered and shared.
        </li>
        <li>
          Do not upload other people&apos;s personal information without their
          knowledge.
        </li>
      </ul>

      <h2>Availability</h2>
      <p>
        There is no uptime guarantee. This is a free service that depends on
        several third-party APIs, and any of them can be slow, rate-limited or
        down — in which case generation fails and you are told so. Features may
        change or be removed. Where a change would lose data, you will be asked
        first.
      </p>

      <h2>Ending it</h2>
      <p>
        Stop using it whenever you like. You can delete individual trips from Trip
        Settings, or ask for your whole account to be deleted — see{' '}
        <Link href="/legal/privacy">Deleting your data</Link>. Accounts used to
        attack the service or other users may be suspended.
      </p>

      <h2>Liability</h2>
      <p>
        WanderForge is provided as-is, without warranty, to the fullest extent the
        law where you are allows. It is a free tool with no paid tier, and the
        operator is not liable for losses arising from using it — including travel
        costs, missed bookings or plans that turned out to be wrong. Nothing here
        excludes liability that cannot lawfully be excluded.
      </p>

      <h2>The software itself</h2>
      <p>
        The source is available under the MIT licence, which covers the code. It
        does not cover this hosted instance or the data in it.
      </p>

      <h2>Governing law</h2>
      <p>These terms are governed by the law of {GOVERNING_LAW}.</p>

      <h2>Changes</h2>
      <p>
        If these terms change, the date at the top changes with them. Continuing
        to use the service after that is acceptance.
      </p>

      <h2>Contact</h2>
      <p>Questions: {CONTACT}.</p>

      <p className="legal__nav">
        <Link href="/legal/privacy">Privacy Policy</Link> · <Link href="/">Home</Link>
      </p>
    </article>
  );
}
